### ISSUE TITLE
hlog transformation and negative values

### ISSUE THREAD

**Issue by msouri** [eyurtsev/FlowCytometryTools#14]
Hello,
congratulations, you have done a great tool. I however encounter problems with negative minimale values [-1 0] and new scales after an hlog transformations. With such minimales values, lxmin is <0 (log10(abs(xmin))) and f also. You should improve this point in next version. I added one test to slove this trouble : 
if lmin<0: f=-lxmin/(-lxmin+lmax)
else : same ...
regards,
Marc

**Comment by eyurtsev** [comment]
This commit should fix this: https://github.com/eyurtsev/FlowCytometryTools/commit/f50fd1165d4e74c4e2b2a3d6b642f882f6e549ad
