### ISSUE TITLE
Is there a way to conda install it?

### ISSUE THREAD

**Issue by monchin** [eyurtsev/FlowCytometryTools#22]
The tutorial on [How to install](https://eyurtsev.github.io/FlowCytometryTools/install.html) just shows `pip install`, and I'm wondering if there is a way to <b>conda</b> install it. I googled but didn't find it.

**Comment by eyurtsev** [comment]
I don't really work with Conda, but if someone wants to add instructions on how to make it work with Conda i'd be happy to merge the PR
