### ISSUE TITLE
"500: Internal Server Error" when using gui with backend='webagg'

### ISSUE THREAD

**Issue by monchin** [eyurtsev/FlowCytometryTools#23]
I used jupyter notebook and followed the tutorial, when I input
```
tsample.view_interactively(backend='webagg')
```
but the page `127.0.0.1:8080` shows `500: Internal Server Error` and nothing else.
Then I looked the jupyter notebook information, and I saw
```
Traceback (most recent call last):
  File "/home/mon/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/mon/anaconda3/lib/python3.6/site-packages/FlowCytometryTools/gui/webagg_backend/gui.py", line 35, in get
    with open(app_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mon/anaconda3/lib/python3.6/site-packages/FlowCytometryTools/gui/webagg_backend/app_template.html'
ERROR:tornado.access:500 GET / (127.0.0.1) 1.07ms
```
It seems that I lack the file `/FlowCytometryTools/gui/webagg_backend/app_template.html`, and I did not found it, which caused the error. So why didn't I have that file? How to save this problem?
Thank you！

**Comment by giometz** [comment]
I had the same issue, and solved it by downloading the file from here [file:///Users/giometto/miniconda2/lib/python2.7/site-packages/FlowCytometryTools/gui/webagg_backend/app_template.html](file:///Users/giometto/miniconda2/lib/python2.7/site-packages/FlowCytometryTools/gui/webagg_backend/app_template.html)
