### ISSUE TITLE
Use of deprecated function from matplotlib in docs

### ISSUE THREAD

**Issue by rpgoldman** [eyurtsev/FlowCytometryTools#25]
When I load `FlowCytometryTools` now, I get this warning message:
```
/Users/rpg/.virtualenvs/xplan-dev-env/lib/python3.6/site-packages/FlowCytometryTools/core/docstring.py:56: MatplotlibDeprecationWarning: 
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
  doc = dedent(doc)
```

It looks like this has been fixed in source, but PyPi still has an old version with the deprecated function.  Would it be possible to make a release?

**Comment by eyurtsev** [comment]
Done! And it only took a year!
