### ISSUE TITLE
Subsampling function not working

### ISSUE THREAD

**Issue by b-robison** [eyurtsev/FlowCytometryTools#27]
Hello,

I'm struggling to figure out what to provide the subsampling method. From the API documentation it looks like there should be three items fed to the method:

![image](https://user-images.githubusercontent.com/63268511/99609504-e4917980-29c4-11eb-8214-6427201e8cc1.png)

However in the source it looks like it wants four items. 

![image](https://user-images.githubusercontent.com/63268511/99609942-af395b80-29c5-11eb-8104-e8fe7eac2cc3.png)

I'm starting with a 20,000 event FCMeasurement object and I want to subsample 1000 events randomly.

![image](https://user-images.githubusercontent.com/63268511/99609857-82854400-29c5-11eb-9b86-5a7d5fd9b067.png)

Following the API documentation I try: 

`tsample.subsample(1000, order='random', auto_resize=False)`

But I get a TypeError:
`TypeError: Population must be a sequence or set.  For dicts, use list(d).`

So trying the four inputs implied by the source code, I get the following error:

![image](https://user-images.githubusercontent.com/63268511/99610504-d2b0d600-29c6-11eb-8d9c-2c1280ebfbf9.png)

Would love to get this subsampling feature working. Thanks!

**Comment by eyurtsev** [comment]
Hi! 

As far as I can tell sub-sampling is working properly. (Though the documentation isn't amazing I must admit.)

![image](https://user-images.githubusercontent.com/3205522/105648162-051ff900-5e78-11eb-8822-8101e1463a03.png)

My guess is that there's something else that's wrong in the code...

Regarding 3 vs. 4 parameters -- you should google for what "self" does in python. There are a lot of excellent articles that will explain it better than I can. :`) (but you only need to pass 3 parameters, the `self` parameter is "auto-filled")
