### ISSUE TITLE
FlowCytometryTools won't import

### ISSUE THREAD

**Issue by clareabreu** [eyurtsev/FlowCytometryTools#29]
I am having trouble importing FlowCytometryTools, getting this error: "ImportError: cannot import name 'dedent' from 'matplotlib.cbook' "

**Comment by eyurtsev** [comment]
Hello! will try to take a look over the weekend, we haven't done maintenance on the package  in a while so it probably fell behind some of its dependencies (like matplotilb)

**Comment by clareabreu** [comment]
> Hello! will try to take a look over the weekend, we haven't done maintenance on the package in a while so it probably fell behind some of its dependencies (like matplotilb)

Thanks!

**Comment by eyurtsev** [comment]
Should be fixed (at least with python 3.6) 

Try install flowcytometry==0.5.1 from the pypi servers
