### ISSUE TITLE
documentation figures are 404'd

### ISSUE THREAD

**Issue by crmackay** [eyurtsev/FlowCytometryTools#7]
a number of the figures on the github.io doc site (especially in the tutorial) are not found. Examples:

- http://eyurtsev.github.io/build/html/_static/2d_plot_B.png Failed to load resource: the server responded with a 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/1d_plot.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/gate_A_plot.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/2d_scatter_plot_A.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/2d_plot_A.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/1d_plot_prettier.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/gated_sample_only_plot.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/gate_D_plot.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/plate_plot_A.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/plate_plot_B.png Failed to load resource: the server responded with a status of 404 (Not Found)
- http://eyurtsev.github.io/build/html/_static/plate_indexing_A.png Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by eyurtsev** [comment]
Thanks! Will fix tonight

**Comment by eyurtsev** [comment]
Again thanks for reporting this! Should be fixed now.
